- name: Test
on:
  push:
    branches:
      - pipelines
jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'


      - name: Get Current Branch
          - shell: bash
          - run : echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          - id : extract_branch

      - name: Unit tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
          name: report.xml
          path: ${{ github.workspace }}/app/build/reports/tests/testDebugUnitTest/index.html

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.1
        with:
          path: ${{ github.workspace }}/app/build/reports/tests/testDebugUnitTest/index.html
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          debug-mode: false

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
